### ISSUE TITLE
error when visuzlization

### ISSUE THREAD

**Issue by jianshu93** [koesterlab/alignoth#58]
Hello Team,

what could be the error here:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /storage/home/hcoda1/4/jzhao399/.cargo/registry/src/github.com-1ecc6299db9ec823/alignoth-0.6.0/src/plot.rs:30:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thanks,

Jianshu

**Comment by fxwiegand** [comment]
Hi there,

the corresponding line in the code is 

```rust
let tid = bam.header().tid(region.target.as_bytes()).unwrap() as i32;
```

This suggests the given target (e.g. `chr1`) is not present in your bam header or probably even file in general. The error message could be improved quite heavily on our side here. I'll try to fix that asap so please keep this issue open until then.

Hope this helps,
Felix

**Comment by jianshu93** [comment]
Hello Felix,

I am visualization a bam file from a bacterial genome (not human genome) and it is fragmented. There is not chr1 or something, each fragment is like bacterial name_1 or something. I was using bwa mem to mapping not Bowtie2.

Thanks,

Jianshu

**Comment by johanneskoester** [comment]
@jianshu93 sure, the chr1 was just and example. Could be any other contig name that causes the failure here. I've just released version 0.6.1, which will provide a better error message that hopefully solves your problem by telling you what is wrong with your input. In case there is still an issue with 0.6.1, please feel free to reopen this issue or open a new one. Thanks!

**Comment by fxwiegand** [comment]
Hi @var-chenm4680 

would you be able to post the contents of you fasta index file here (`ref_1.fna.fai`)? I went through the code and couldn't really find any other option than something being wrong with the reference length. In case your data is not sensitive it'd also be very helpful for debugging. Would you be able to provide it?

**Comment by fxwiegand** [comment]
So I have investigated a bit - thanks for providing the data - really an edge case you brought to the table! The root cause seems to be a read starting at position 0 and also starting with 10 softclips. With our current region fetching this therefore results in a region starting at -10 (which can't be fetched of course):
```rust
let region = cli::Region {
            target: target.to_string(),
            start: record.pos() - record.cigar().leading_softclips(),
            end: record.reference_end() + record.cigar().trailing_softclips(),
        };
```

What we should do instead I think is fetch the region only via `record.pos()` and then skip any leading/trailing soft clips in our align function.

**Comment by var-chenm4680** [comment]
Wow — thank you very much for digging into this in such detail. This is a brilliant catch, and I really appreciate the clear explanation of the root cause and the proposed fix.

While working with this dataset, I noticed a related phenomenon: in my BAM file, almost all reads contain soft-clipped bases. For example, running
awk '$6 ~ /S/ {c++} END{print c}'
shows that ~99% of the reads include soft clipping.

In a reference-guided alignment framework, this behavior is not easy to perceive in IGV, since everything is displayed in reference coordinates. At the same time, I fully understand that it would be unreasonable to expect a reference-based visualization or plotting tool to explicitly display soft-clipped regions, as that would significantly complicate the design. Still, I suspect these soft-clipped bases may not be entirely uninformative, as they could reflect sequence content beyond the provided reference. I am still exploring this aspect.

Regarding your proposed solution: if I understand it correctly, the idea is to restrict region fetching strictly to reference coordinates (i.e. using record.pos() and record.reference_end() only), and then handle leading and trailing soft clips later during the alignment or plotting step, rather than expanding the fetched region based on soft-clipped bases. This separation of concerns makes a lot of sense to me, and I just wanted to confirm that this is indeed the intended direction, especially for reads starting at position 0 with leading soft clips.

If possible, would you be willing to share a small code snippet or example illustrating this approach in practice? Being able to run a concrete example on my data would greatly help me better internalize how record.pos()–based region handling is intended to work.

Thanks again for the excellent support and for improving alignoth. I also briefly asked by email about general experience or advice on consensus sequence generation;  and would appreciate any thoughts if convenient.
